export const LOGIN_SUCCESS = "REGISTER-LOGIN-RESPONSE/SING-IN/LOGIN-SUCCESS";
export const LOGIN_ERROR = "REGISTER-LOGIN-RESPONSE/SING-IN/LOGIN_ERROR";
export const LOGIN_IS_LOADING = "REGISTER-LOGIN-RESPONSE/SING-IN/LOGIN_IS_LOADING";

interface ISomeAction {
    type: string;
}

export type ISignInActions = ISomeAction ;
